// Command genassets compiles the bundled font and icon files into Go source
// (internal/ui/assets_gen.go) so they are baked into the binary WITHOUT any
// //go:embed directive. The generator itself reads the files from disk; the
// resulting source carries the bytes as base64 string literals.
//
// Run from the repository root (see the Makefile `generate` target):
//
//	go run ./tools/genassets
//
// Regenerate after adding/changing files under internal/ui/fonts or
// internal/ui/icons.
package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
)

const (
	uiDir   = "internal/ui"
	outFile = "internal/ui/assets_gen.go"
)

// globs of bundled assets, relative to uiDir.
var globs = []string{"fonts/*.ttf", "icons/*.svg"}

type asset struct {
	key string // path under internal/ui, slash-separated (e.g. "fonts/X.ttf")
	b64 string // base64 of the file bytes
}

func main() {
	assets := collect()

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genassets; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `make generate` after changing files under fonts/ or icons/.\n\n")
	b.WriteString("package ui\n\n")
	b.WriteString("import \"encoding/base64\"\n\n")
	b.WriteString("// mustB64 decodes a base64 asset string, panicking on corruption.\n")
	b.WriteString("func mustB64(s string) []byte {\n")
	b.WriteString("\tb, err := base64.StdEncoding.DecodeString(s)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tpanic(\"ui: corrupt bundled asset: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn b\n")
	b.WriteString("}\n\n")
	b.WriteString("// embeddedAssets holds every bundled asset keyed by its path under internal/ui.\n")
	b.WriteString("var embeddedAssets = map[string][]byte{\n")
	for _, a := range assets {
		fmt.Fprintf(&b, "\t%q: mustB64(%q),\n", a.key, a.b64)
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("genassets: format generated source: %v", err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		log.Fatalf("genassets: write %s: %v", outFile, err)
	}
	fmt.Printf("genassets: wrote %d assets to %s\n", len(assets), outFile)
}

// collect reads every matching asset file and returns them sorted by key so
// regeneration is deterministic.
func collect() []asset {
	var assets []asset
	for _, g := range globs {
		matches, err := filepath.Glob(filepath.Join(uiDir, g))
		if err != nil {
			log.Fatalf("genassets: glob %q: %v", g, err)
		}
		if len(matches) == 0 {
			log.Fatalf("genassets: no files matched %q (run from the repo root)", g)
		}
		for _, m := range matches {
			data, err := os.ReadFile(m)
			if err != nil {
				log.Fatalf("genassets: read %q: %v", m, err)
			}
			rel, err := filepath.Rel(uiDir, m)
			if err != nil {
				log.Fatalf("genassets: rel %q: %v", m, err)
			}
			assets = append(assets, asset{
				key: filepath.ToSlash(rel),
				b64: base64.StdEncoding.EncodeToString(data),
			})
		}
	}
	sort.Slice(assets, func(i, j int) bool { return assets[i].key < assets[j].key })
	return assets
}
